filename: stage1_dqw2d_test

strategy_name: deepspeed
accelerator: gpu
precision: bf16-mixed
max_epochs: 6
check_val_every_n_epoch: 3
save_every_n_epochs: 3
accumulate_grad_batches: 1

weight_decay: 0.05
init_lr: 1.0e-4
min_lr: 1.0e-5
warmup_lr: 1.0e-6
warmup_steps: 500
scheduler: linear_warmup_cosine_lr


tune_gnn: False
temperature: 0.1
enable_blending: True
use_flash_attention: True
use_dq_encoder: True
local_q_only: False
brics_gids_enable: True
entropy_gids_enable: True